site_name: Yuzu Inventory System
nav:
  - Home: index.md
  - Features: features.md
  - Installation: installation.md
  - Usage:
    - Basic Usage: scripting.md
    - Item Interaction: item-interaction.md
theme: material
